TARGET_VELOCITY: 0.8
# PREDICT_TIME: 1.5
#PREDICT_TIME: 2.5
PREDICT_TIME: 2.5   # 3.3 3.0
OBSTACLE_COST_GAIN: 0.9 #2.0 1
TO_GOAL_COST_GAIN: 3.5
SPEED_COST_GAIN: 0.5
PATH_COST_GAIN: 0.8 #0.7  # 0.9
ANGLE_RESOLUTION: 0.2
DT: 0.1
GOAL_THRESHOLD: 0.30
#TURN_DIRECTION_THRESHOLD: 0.5
TURN_DIRECTION_THRESHOLD: 2.5
ANGLE_TO_GOAL_TH: pi
SIM_DIRECTION: 1.57
SLOW_VELOCITY_TH: 0.1
OBS_RANGE: 2.5
VELOCITY_SAMPLES: 20
YAWRATE_SAMPLES: 20
